#!/bin/bash

echo "Cleaning..."

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Participant 1: Solid
Participant1="solid"
rm -fv ${Participant1}/solid.mess
rm -fv ${Participant1}/solid.resu
rm -fv ${Participant1}/solid.rmed

# Participant 2: Fluid
Participant2="fluid"
cd ${Participant2}
  cleanCase
  touch Fluid.foam
cd ..
# Remove the log files
rm -fv ${Participant2}_blockMesh.log
rm -fv ${Participant2}_checkMesh.log
rm -fv ${Participant2}_decomposePar.log
rm -fv ${Participant2}.log
rm -fv ${Participant2}_reconstructPar.log

# Remove the preCICE-related log files
echo "Deleting the preCICE log files..."
rm -fv \
    precice-*.log \
    precice-*-events.json

# Output files for preCICE versions before 1.2:
rm -fv \
    iterations-${Participant1}.txt iterations-${Participant2}.txt \
    convergence-${Participant1}.txt convergence-${Participant2}.txt \
    Events-${Participant1}.log Events-${Participant2}.log \
    EventTimings-${Participant1}.log EventTimings-${Participant2}.log

# Remove the preCICE address files
rm -rfv precice-run
rm -fv .*.address

echo "Cleaning complete!"
